{
	"editor.wordWrap": "on",
	"editor.renderWhitespace": "none",
	"editor.formatOnType": true,
	"editor.formatOnPaste": false,
	"editor.renderControlCharacters": false,
	"editor.detectIndentation": false,
	"editor.insertSpaces": false,
	"editor.tabSize": 2,
	"editor.bracketPairColorization.enabled": true,
	"editor.hover.enabled": true,
	"editor.minimap.enabled": false,
	"editor.scrollbar.vertical": "visible",
	"editor.scrollbar.horizontal": "visible",
	"breadcrumbs.enabled": false,
	"workbench.startupEditor": "none",
	"editor.formatOnSave": true,
	"[javascript]": {
		"editor.formatOnSave": true,
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"prettier.singleQuote": true,
	"javascript.suggest.completeFunctionCalls": true,
	"editor.cursorBlinking": "expand",
	"editor.cursorWidth": 3,
	"editor.linkedEditing": true,
	"editor.snippetSuggestions": "top",
	"javascript.suggest.names": false,
	"javascript.updateImportsOnFileMove.enabled": "always",
	"html.format.indentInnerHtml": true,
	"emmet.showSuggestionsAsSnippets": true,
	"workbench.editor.wrapTabs": true,
	"workbench.colorCustomizations": {
		"editorCursor.foreground": "#ff2c1d",
		"tab.activeBorder": "#ff2c1d",
		"editorSuggestWidget.selectedBackground": "#ff00005e",
		"editor.snippetTabstopHighlightBackground": "#282C34",
		"terminal.background": "#21252B",
		// "editorError.foreground": "#FFA500",
		"editorWarning.foreground": "#ff9248",
		"editorInfo.foreground": "#00C0A3"
	},
	"explorer.confirmDragAndDrop": false,
	"terminal.integrated.fontSize": 15,
	"editor.fontSize": 17,
	"editor.letterSpacing": 0.1,
	"[Log]": {
		"editor.fontSize": 12
	},
	"security.workspace.trust.untrustedFiles": "open",
	"emmet.excludeLanguages": ["markdown", "javascript", "php"],
	"explorer.confirmDelete": false,
	"terminal.integrated.enableMultiLinePasteWarning": false,
	"typescript.suggest.paths": true,
	"javascript.suggest.paths": false,
	"debug.javascript.autoAttachFilter": "disabled",
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": "never",
		"source.fixAll.tslint": "never"
	},
	"editor.fontWeight": "300",
	"editor.lineHeight": 1.3,
	"workbench.editor.enablePreview": false,
	"workbench.tree.indent": 8,
	"workbench.tree.renderIndentGuides": "always",
	"editor.semanticHighlighting.enabled": true,
	"explorer.compactFolders": false,
	"editor.fontFamily": "JetBrains Mono Thin",
	"editor.fontLigatures": true,
	"editor.guides.bracketPairs": "active",
	"window.zoomLevel": -0.6,
	"editor.renderLineHighlight": "none",
	"terminal.integrated.defaultProfile.windows": "Git Bash",
	"liveServer.settings.donotShowInfoMsg": true,
	"editor.accessibilitySupport": "off",
	"typescript.validate.enable": true,
	"javascript.validate.enable": true,
	"editor.accessibilityPageSize": 1,
	"editor.quickSuggestionsDelay": 10,
	"search.exclude": {
		"**/.git": true,
		"**/node_modules": true,
		"**/bower_components": true,
		"**/tmp": true
	},
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"typescript.format.enable": false,
	"emmet.includeLanguages": {
		"javascript": "javascriptreact",
		"ejs": "html"
	},
	"workbench.colorTheme": "One Dark Pro",
	"telemetry.telemetryLevel": "off",
	"workbench.enableExperiments": false,
	"workbench.iconTheme": "vscode-icons",
	"vsicons.dontShowNewVersionMessage": true,
	"[json]": {
		"editor.defaultFormatter": "vscode.json-language-features"
	},
	"editor.suggest.snippetsPreventQuickSuggestions": false,
	// "update.mode": "none",
	"git.suggestSmartCommit": false,
	"git.confirmSync": false,
	"window.commandCenter": false,
	"workbench.layoutControl.enabled": false,
	"zenMode.hideActivityBar": false,
	"workbench.activityBar.location": "top",
	"extensions.ignoreRecommendations": true,
	"eslint.rules.customizations": [
		{ "rule": "no-unused-vars", "severity": "warn" },
		{ "rule": "!no-*", "severity": "downgrade" },
		{ "rule": "radix", "severity": "default" }
	],
	"eslint.workingDirectories": ["./backend", "./frontend"],
	"eslint.debug": true,
	"editor.suggest.showStatusBar": true,
	"eslint.codeAction.showDocumentation": {
		"enable": true
	},
	"eslint.nodePath": "C:\\{path}",
	"css.lint.unknownAtRules": "ignore"
}
